[clean]
description = "Remove all untracked or safe to remove files"
run = "git clean -fdx -e .env"

[serve]
description = "Serve the app with live preview"
run = "npx vite --open --host"

[lint]
description = "Lint all files"
run = ["mise fmt", "npm run check", "npm run compile"]
